# Generated by Django 2.0.5 on 2018-08-09 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bCoreRiskApp', '0002_auto_20180809_2230'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskfield',
            name='field_type',
            field=models.CharField(choices=[('T', 'Text'), ('N', 'Number'), ('D', 'Date'), ('E', 'Enum')], default='T', max_length=1),
        ),
    ]
