# Generated by Django 2.0.5 on 2018-08-09 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bCoreRiskApp', '0003_riskfield_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfield',
            name='risk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='bCoreRiskApp.Risk'),
            preserve_default=False,
        ),
    ]
