# Generated by Django 2.0.5 on 2018-08-10 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bCoreRiskApp', '0006_auto_20180810_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfield',
            name='field_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskfield',
            name='field_enum_text',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='riskfield',
            name='field_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='riskfield',
            name='field_num',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskfield',
            name='field_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='riskfield',
            name='field_type',
            field=models.CharField(choices=[('T', 'Text'), ('N', 'Number'), ('D', 'Date'), ('E', 'Enum')], max_length=1),
        ),
    ]
