# Generated by Django 2.0.5 on 2018-08-14 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bCoreRiskApp', '0007_auto_20180810_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfield',
            name='field_name',
            field=models.CharField(max_length=200),
        ),
    ]
