# Generated by Django 2.0.5 on 2018-08-16 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bCoreRiskApp', '0008_auto_20180814_0742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.CharField(default='Choice Text', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='riskfield',
            name='field_text',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='riskfield',
            name='risk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_fields', to='bCoreRiskApp.Risk'),
        ),
    ]
