# Generated by Django 2.0.5 on 2018-08-17 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bCoreRiskApp', '0009_auto_20180816_2342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='riskfield',
            name='field_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
