# Generated by Django 2.0.5 on 2018-08-17 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bCoreRiskApp', '0010_auto_20180817_2003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='riskfield',
            name='field_enum_text',
        ),
        migrations.AddField(
            model_name='riskfield',
            name='field_enum',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
